import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: false, args: ['--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 900, height: 520 } });
page.on('pageerror', (e) => console.log('ERR', e.message.split('\n')[0]));
await page.goto('http://localhost:5173/play/burnout/', { waitUntil: 'domcontentloaded' });
const t0 = Date.now();
while (Date.now() - t0 < 40000) { if (await page.evaluate(() => window.__READY__ === true).catch(() => false)) break; await page.waitForTimeout(100); }
await page.mouse.click(450, 260);
await page.waitForTimeout(5000);
const cv = page.locator('canvas').first();
await cv.screenshot({ path: '.scratch-burnout/ab-0-base.png' });
await page.evaluate(() => { const g = window.__CRASHOUT__; g.step = () => {}; g.updateCamera = () => {}; g.updateLighting = () => {}; g.world.update = () => {}; });
await page.waitForTimeout(300);
await cv.screenshot({ path: '.scratch-burnout/ab-1-frozen.png' });
await page.evaluate(() => { window.__CRASHOUT__.post.u.uBloom.value = 0; });
await page.waitForTimeout(300);
await cv.screenshot({ path: '.scratch-burnout/ab-2-nobloom.png' });
await page.evaluate(() => { window.__CRASHOUT__.post.u.uExposure.value = 0.02; });
await page.waitForTimeout(300);
await cv.screenshot({ path: '.scratch-burnout/ab-3-lowexp.png' });
await page.evaluate(() => { const g = window.__CRASHOUT__; g.post.u.uExposure.value = 0.17; g.sun.intensity = 0; g.hemi.intensity = 0; g.scene.environmentIntensity = 0; });
await page.waitForTimeout(300);
await cv.screenshot({ path: '.scratch-burnout/ab-4-nolight.png' });
await browser.close();
